use customer_shopping;
select * from customers limit 10; 

# 1.what is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue 
from customers
group by gender;


# 2.which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount 
from customers
where discount_applied ='yes' and purchase_amount >= (select avg(purchase_amount));


# 3.which are the top 5 products with the highest average review rating?
select item_purchased ,round(avg(review_rating),2) as "Average product rating"
from customers
group by item_purchased 
order by avg(review_rating) desc limit 5;


# 4.compare the average purchase amounts between standard and express shipping
select shipping_type , round(avg(purchase_amount),2) from customers
where shipping_type in('Standard','Express')
group by shipping_type;


# 5.do subscribed customers spend more?compare average spend and total revenue between subscribers and non
select subscription_status , count(customer_id) as total_customers ,round(avg(purchase_amount),2) as avg_spend ,
round(sum(purchase_amount),2) as total_revenue from customers
group by subscription_status order by total_revenue, avg_spend desc;


# 6.which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*) * 100,2) as discount_rate
from customers 
group by item_purchased order by discount_rate desc limit 5;


# 7.are customers who are repeat buyers (more than 5 previous purchases) are also a subscribers?
select subscription_status, count(customer_id) as repeat_buyers from customers
where previous_purchases > 5
group by subscription_status;


# 8.what is revenue contribution of each age group?
select age_group, sum(purchase_amount) as total_revenue from customers 
group by age_group
order by total_revenue desc;